SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `topic`;
TRUNCATE TABLE `chapter`;
TRUNCATE TABLE `test`;
TRUNCATE TABLE `question`;
TRUNCATE TABLE `question_chapter`;
TRUNCATE TABLE `answer`;

SET FOREIGN_KEY_CHECKS = 1;